apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyx-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: moneyx-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: moneyx-frontend
        image: moneyx.azurecr.io/moneyx-frontend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: moneyx-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: moneyx-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyx-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyx-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: moneyx-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: moneyx-backend
        image: moneyx.azurecr.io/moneyx-backend:latest
        # ports:
        # - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangonv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangonv
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: djangonv
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: djangonv
        image: moneyx.azurecr.io/djangonv:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: djangonv
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: djangonv