#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: Container Scan 

on:
  registry_package:
    types: [published,updated]
jobs:      
    Container_Scan:
       runs-on: ubuntu-latest
       steps:
         - name: Deep Security Smart Check Scan ECR
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.0
           with:
              DSSC_IMAGE_NAME: 650143975734.dkr.ecr.us-east-1.amazonaws.com/djangonv
              DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
              DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
              DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
              DSSC_IMAGE_PULL_AUTH: ${{ secrets.DSSC_IMAGE_PULL_AUTH }}
              DSSC_FINDINGS_THRESHOLD: '{"malware": 999, "vulnerabilities": { "defcon1": 999, "critical": 999, "high": 999 }, "contents": { "defcon1": 999, "critical": 999, "high": 999 }, "checklists": { "defcon1": 999, "critical": 999, "high": 999 }}'
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
         - name: Deep Security Smart Check Scan ACR
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.0
           with:
              DSSC_IMAGE_NAME: krish.azurecr.io/alpine
              DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
              DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
              DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
              DSSC_IMAGE_PULL_AUTH: '{"username": "${{ secrets.ACR_USER }}","password": "${{ secrets.ACR_PASSWORD }}"}'
              DSSC_FINDINGS_THRESHOLD: '{"malware": 999, "vulnerabilities": { "defcon1": 999, "critical": 999, "high": 999 }, "contents": { "defcon1": 999, "critical": 999, "high": 999 }, "checklists": { "defcon1": 999, "critical": 999, "high": 999 }}'
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
         - name: Cointainer Successfully Scanned
           run : echo "CI Pipeline part finished successfully"
    Dev_Tests:
        runs-on: ubuntu-latest
        needs: [Container_Image_Scan]
        steps:
         - name: Dev Tests
           run: echo Dev Tests
      
         - name: Unit Tests
           run: echo Unit Tests
           
         - name: Dev Tests part finished successfully
           run : echo "Dev Tests part finished successfully"