#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: infrastructure-deploy

on: 
  push:
    branches: 
      - master
      
jobs:      
    Cloud-One-Conformity-Scan-Security:
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v2
          - name: Cloud One Conformity Pipeline Scanner
            uses: raphabot/conformity-template-scanner-pipeline@v1.0.0
            env:
              cc_apikey: ${{ secrets.apikey }}
              maxExtreme: 0
              maxVeryHigh: 1
              macHigh: 3
              maxMedium: 5
              maxLow: 10
              cc_region: us-west-2
              templatePath: infrastructure.yaml
