#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: infrastructure-deploy

on: 
  push:
    branches: 
      - master
      
jobs:      
    Cloud-One-Conformity-Scan-Security:
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v2
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1
          - name: AWS CF Deploy Tests
            run: aws cloudformation validate-template --region us-east-1 --template-body file://infrastructure.yaml
          - name: Cloud One Conformity Pipeline Scanner
            uses: raphabot/conformity-template-scanner-pipeline@v1.0.0
            env:
              cc_apikey: ${{ secrets.apikey }}
              maxExtreme: 0
              maxVeryHigh: 10
              macHigh: 10
              maxMedium: 10
              maxLow: 10
              cc_region: us-west-2
              templatePath: infrastructure.yaml
