name: CI/CD DSSC

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Snyk CLI Action
      uses: clarkio/snyk-cli-action@1.0.0
    - name: Container Build
      run: echo Container Build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
    - name: Cloud One Container Image Scan
      run: echo Cloud One Container Image Scan
    - name: Dev Tests
      run: echo Dev Tests
    - name: Unit Tests
      run: echo Unit Tests
    - name: Deploy Tests
      run: echo Deploy Tests
    - name: Deploy Cloud One Application Protection
      run: echo Deploy Cloud One Application Protection
    - name: Deploy
      run: echo Deploy to Fargate
    - name: Slack Notification
      run: echo Deploy Tests
