#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: Build_and_Push

env:
  PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_API }}

on: 
  push:
    branches: 
      - master
      
jobs:      
    Source_Code_Test:
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v2
    Build_and_Push:
        runs-on: ubuntu-latest
        steps:
          - name: Container Build
            run : |
              cd frontend && docker build -t moneyx-frontend:latest .
              cd ../backend && docker build -t moneyx-backend:latest .
              cd ../djangonv && docker build -t djangonv:latest .
          - name: Github Packages Login
            run: docker login docker.pkg.github.com -u felipecosta09 -p ${{ secrets.PACKAGES_TOKEN }}
          - name: Tag Docker Image
            run: |
              docker tag moneyx-frontend docker.pkg.github.com/felipecosta09/demo-cloud-one/moneyx-frontend:latest
              docker tag moneyx-backend docker.pkg.github.com/felipecosta09/demo-cloud-one/moneyx-backend:latest
              docker tag djangonv docker.pkg.github.com/felipecosta09/demo-cloud-one/djangonv:latest
          - name: Push Docker Image to Github Packages
            run: |
              docker push docker.pkg.github.com/felipecosta09/demo-cloud-one/moneyx-frontend:latest
              docker push docker.pkg.github.com/felipecosta09/demo-cloud-one/moneyx-backend:latest
              docker push docker.pkg.github.com/felipecosta09/demo-cloud-one/djangonv:latest