#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: Deep Security Smart Check

env:
    # DSSC_SMARTCHECK_HOST : ${{ secrets.DSSC_SMARTCHECK_HOST }}
    # DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
    # DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    DSSC_IMAGE_PULL_AUTH: '{aws":{"region":"us-east-1","accessKeyID":"$AWS_ACCESS_KEY_ID","secretAccessKey":"$AWS_SECRET_ACCESS_KEY"}}'

on: 
  push:
    branches: 
      - master
      

jobs:      
    Scan-Action:
       runs-on: ubuntu-latest
       steps:
       - name: Deep Security Smart Check
         uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.6-alpha
         env:
          DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
          DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
          DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
          DSSC_INSECURE_SKIP_TLS_VERIFY: true;
          DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true;
          DSSC_IMAGE_NAME: 650143975734.dkr.ecr.us-east-1.amazonaws.com/djangonv
          # DSSC_IMAGE_PULL_AUTH: '{"aws":{"region":"us-east-1","accessKeyID":"'${{ secrets.AWS_ACCESS_KEY_ID }}'","secretAccessKey":"'${{ secrets.AWS_SECRET_ACCESS_KEY }}'"}}'
          # DSSC_IMAGE_PULL_AUTH: {"username":"<user>","password":"<password>"} 
          #{aws":{"region":"us-east-1","accessKeyID":"'$AWS_ACCESS_KEY_ID'","secretAccessKey":"'$AWS_SECRET_ACCESS_KEY'"}}
           
         # - name: Deep Security Smart Check Scan
         #  uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.5-alpha
         
         # - name: "Deep Security Smart Check Scan Action"
           # env:
            # DSSC_SMARTCHECK_HOST : ${{ secrets.DSSC_SMARTCHECK_HOST }}
            # DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
            # DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
            # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           # run: docker run -v /var/run/docker.sock:/var/run/docker.sock deepsecurity/smartcheck-scan-action --image-name=650143975734.dkr.ecr.us-east-1.amazonaws.com/djangonv --smartcheck-host=$DSSC_SMARTCHECK_HOST --smartcheck-user=$DSSC_SMARTCHECK_USER --smartcheck-password=$DSSC_SMARTCHECK_PASSWORD --insecure-skip-tls-verify --insecure-skip-registry-tls-verify --image-pull-auth='{"aws":{"region":"us-east-1","accessKeyID":"'$AWS_ACCESS_KEY_ID'","secretAccessKey":"'$AWS_SECRET_ACCESS_KEY'"}}' --findings-threshold '{"malware":999,"vulnerabilities":{"defcon1":999,"critical":999,"high":999},"contents":{"defcon1":999,"critical":999,"high":999},"checklists":{"defcon1":999,"critical":999,"high":999}}'
