#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: Protect CI/CD Pipelines

on: 
  push:
    branches: 
      - master

jobs:      
    Container_Image_Scan:
       runs-on: ubuntu-latest
       steps:
         - name: Git Checkout
           uses: actions/checkout@v2
         
         - name: "Cloud One Container Image Scan"
           run: docker run -v /var/run/docker.sock:/var/run/docker.sock deepsecurity/smartcheck-scan-action --image-name=650143975734.dkr.ecr.us-east-1.amazonaws.com/djangonv --smartcheck-host=container-security.tmselabs.com --smartcheck-user=felipe_costa --smartcheck-password=Trend@00p$ --insecure-skip-tls-verify --insecure-skip-registry-tls-verify --image-pull-auth='{"aws":{"region":"us-east-1","accessKeyID":"'$AWS_ACCESS_KEY_ID'","secretAccessKey":"'$AWS_SECRET_ACCESS_KEY'"}}' --findings-threshold '{"malware":100,"vulnerabilities":{"defcon1":100,"critical":100,"high":100},"contents":{"defcon1":100,"critical":100,"high":100},"checklists":{"defcon1":100,"critical":100,"high":100}}'