#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: Protect CI/CD Pipelines

on: 
  push:
    branches: 
      - master

jobs:      
    Container_Image_Scan:
       runs-on: ubuntu-latest
       steps:
         - name: Git Checkout
           uses: actions/checkout@v2
         
         - name: Cloud One Container Image Scan
           uses: "docker://deepsecurity/smartcheck-scan-action"
           with:
              args: "--version"
