#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: Deep Security Smart Check

on: 
  push:
    branches: 
      - master
      
jobs:      
    SmartCheck-Scan-Action:
       runs-on: ubuntu-latest
       steps:
        - name: Deep Security Smart Check
          uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.7-alpha
          with:
            # Container repository, eg myorg/myimage.
            DSSC_IMAGE_NAME: 650143975734.dkr.ecr.us-east-1.amazonaws.com/djangonv
            # Deep Security Smart Check url, eg mydomain.com.
            DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
            # Deep Security Smart Check username, eg admin.
            DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
            # Deep Security Smart Check password, eg 12345.
            DSSC_SMARTCHECK_PASS: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
            # Container registry credentials in a json format,  eg '{"username":"<user>","password":"<password>"}' or {"aws":{"region":"us-east-1","accessKeyID":"'AWS_ACCESS_KEY_ID'","secretAccessKey":"'AWS_SECRET_ACCESS_KEY'"}}'
            DSSC_IMAGE_PULL_AUTH:  ${{ secrets.DSSC_IMAGE_PULL_AUTH }}
       # - name: Deep Security Smart Check
         # uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.6-alpha
         # env:
          # DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
          # DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
          # DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
          # DSSC_INSECURE_SKIP_TLS_VERIFY: true;
          # DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true;
          # DSSC_IMAGE_NAME: 650143975734.dkr.ecr.us-east-1.amazonaws.com/djangonv
          # DSSC_IMAGE_PULL_AUTH: ${{ secrets.DSSC_IMAGE_PULL_AUTH }}
